# Generated by Django 2.2.1 on 2019-08-29 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articels_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commen',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='sys_user',
            old_name='sys_user',
            new_name='user',
        ),
    ]
